### ISSUE TITLE
Error compile on kernel 5.13.0-27-generic (x86_64)

### ISSUE THREAD

**Issue by bpranoto** [EnzephaloN/ncpfs_dkms#9]
Hi, there are compilation error on kernel 5.13.0-27-generic (x86_64) with master branch.

I tried to switch to https://github.com/EnzephaloN/ncpfs_dkms/tree/kernel_5.12 branch, however still got the same issue.

Your help is much appreciated, thank you.

[error.log](https://github.com/EnzephaloN/ncpfs_dkms/files/7917907/error.log)

**Comment by EnzephaloN** [comment]
Hi.

Strange. I'm don't know whats wrong there. Maybe you try the kernel_5.6 branch? 

Hope that helps.

**Comment by bpranoto** [comment]
Thanks,

I'lll try on monday, because the computer is in the office

**Comment by bpranoto** [comment]
kernel_5.6 branch cannot be compiled in kernel 5.13.0-27
[make.log](https://github.com/EnzephaloN/ncpfs_dkms/files/7922701/make.log)

**Comment by bpranoto** [comment]
After some searching in google, I found this. It is something related to year 2038 issue with the time_t structure.

[https://patchwork.kernel.org/project/linux-fbdev/patch/20150525040716.GA4448@tinar/](https://patchwork.kernel.org/project/linux-fbdev/patch/20150525040716.GA4448@tinar/)

Could you please investigate?

**Comment by bpranoto** [comment]
I replace all reference  of time_t  into ktime_t in branch master. It compiles and works well. 



[dir.c.diff.txt](https://github.com/EnzephaloN/ncpfs_dkms/files/7923347/dir.c.diff.txt)
[ncplib_kernel.h.diff.txt](https://github.com/EnzephaloN/ncpfs_dkms/files/7923349/ncplib_kernel.h.diff.txt)

**Comment by EnzephaloN** [comment]
Hello
Fine. 
But I don't think this might correct for later kernel. Maybe this yould be the correct patch for 5.13, but I think not for >=5.15.

**Comment by bpranoto** [comment]
Thank you very much for the fix.
