### ISSUE TITLE
Build error on kernel 5.4.0-104

### ISSUE THREAD

**Issue by bpranoto** [EnzephaloN/ncpfs_dkms#10]
Environment:
```
$ cat /etc/issue
Linux Mint 20 Ulyana \n \l
$ uname -a
Linux akunting 5.4.0-104-generic #118-Ubuntu SMP Wed Mar 2 19:02:41 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

Error on compiling dir.c
```
$ cat /var/lib/dkms/ncpfs/2.2.6/build/make.log
DKMS make.log for ncpfs-2.2.6 for kernel 5.4.0-104-generic (x86_64)
Kam 17 Mar 2022 03:50:12  WIB
make -C /lib/modules/5.4.0-104-generic/build M=/var/lib/dkms/ncpfs/2.2.6/build modules
make[1]: Entering directory '/usr/src/linux-headers-5.4.0-104-generic'
  CC [M]  /var/lib/dkms/ncpfs/2.2.6/build/dir.o
/var/lib/dkms/ncpfs/2.2.6/build/dir.c:62:13: error: initialization of ‘int (*)(struct inode *, struct dentry *, umode_t,  bool)’ {aka ‘int (*)(struct inode *, struct dentry *, short unsigned int,  _Bool)’} from incompatible pointer type ‘int (*)(struct user_namespace *, struct inode *, struct dentry *, umode_t,  bool)’ {aka ‘int (*)(struct user_namespace *, struct inode *, struct dentry *, short unsigned int,  _Bool)’} [-Werror=incompatible-pointer-types]
   62 |  .create  = ncp_create,
      |             ^~~~~~~~~~
/var/lib/dkms/ncpfs/2.2.6/build/dir.c:62:13: note: (near initialization for ‘ncp_dir_inode_operations.create’)
/var/lib/dkms/ncpfs/2.2.6/build/dir.c:65:13: error: initialization of ‘int (*)(struct inode *, struct dentry *, const char *)’ from incompatible pointer type ‘int (*)(struct user_namespace *, struct inode *, struct dentry *, const char *)’ [-Werror=incompatible-pointer-types]
   65 |  .symlink = ncp_symlink,
      |             ^~~~~~~~~~~
/var/lib/dkms/ncpfs/2.2.6/build/dir.c:65:13: note: (near initialization for ‘ncp_dir_inode_operations.symlink’)
/var/lib/dkms/ncpfs/2.2.6/build/dir.c:66:12: error: initialization of ‘int (*)(struct inode *, struct dentry *, umode_t)’ {aka ‘int (*)(struct inode *, struct dentry *, short unsigned int)’} from incompatible pointer type ‘int (*)(struct user_namespace *, struct inode *, struct dentry *, umode_t)’ {aka ‘int (*)(struct user_namespace *, struct inode *, struct dentry *, short unsigned int)’} [-Werror=incompatible-pointer-types]
   66 |  .mkdir  = ncp_mkdir,
      |            ^~~~~~~~~
/var/lib/dkms/ncpfs/2.2.6/build/dir.c:66:12: note: (near initialization for ‘ncp_dir_inode_operations.mkdir’)
/var/lib/dkms/ncpfs/2.2.6/build/dir.c:68:12: error: initialization of ‘int (*)(struct inode *, struct dentry *, umode_t,  dev_t)’ {aka ‘int (*)(struct inode *, struct dentry *, short unsigned int,  unsigned int)’} from incompatible pointer type ‘int (*)(struct user_namespace *, struct inode *, struct dentry *, umode_t,  dev_t)’ {aka ‘int (*)(struct user_namespace *, struct inode *, struct dentry *, short unsigned int,  unsigned int)’} [-Werror=incompatible-pointer-types]
   68 |  .mknod  = ncp_mknod,
      |            ^~~~~~~~~
/var/lib/dkms/ncpfs/2.2.6/build/dir.c:68:12: note: (near initialization for ‘ncp_dir_inode_operations.mknod’)
/var/lib/dkms/ncpfs/2.2.6/build/dir.c:69:13: error: initialization of ‘int (*)(struct inode *, struct dentry *, struct inode *, struct dentry *, unsigned int)’ from incompatible pointer type ‘int (*)(struct user_namespace *, struct inode *, struct dentry *, struct inode *, struct dentry *, unsigned int)’ [-Werror=incompatible-pointer-types]
   69 |  .rename  = ncp_rename,
      |             ^~~~~~~~~~
/var/lib/dkms/ncpfs/2.2.6/build/dir.c:69:13: note: (near initialization for ‘ncp_dir_inode_operations.rename’)
/var/lib/dkms/ncpfs/2.2.6/build/dir.c:70:13: error: initialization of ‘int (*)(struct dentry *, struct iattr *)’ from incompatible pointer type ‘int (*)(struct user_namespace *, struct dentry *, struct iattr *)’ [-Werror=incompatible-pointer-types]
   70 |  .setattr = ncp_notify_change,
      |             ^~~~~~~~~~~~~~~~~
/var/lib/dkms/ncpfs/2.2.6/build/dir.c:70:13: note: (near initialization for ‘ncp_dir_inode_operations.setattr’)
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:270: /var/lib/dkms/ncpfs/2.2.6/build/dir.o] Error 1
make[1]: *** [Makefile:1762: /var/lib/dkms/ncpfs/2.2.6/build] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.4.0-104-generic'
make: *** [Makefile:48: all] Error 2

```

Thanks...

**Comment by EnzephaloN** [comment]
Did you use the correct branch?! You have kernel 5.4, so you need https://github.com/EnzephaloN/ncpfs_dkms/tree/kernel_5.2

**Comment by bpranoto** [comment]
My bad.

Yes, it works with kernel_5.2 branch

Sorry/
