### ISSUE TITLE
Build error with kernel 4.19.81: initialization from incompatible pointer type

### ISSUE THREAD

**Issue by phdru** [EnzephaloN/ncpfs_dkms#1]
$ sudo dkms build -k 4.19.81 -m ncpfs -v 2.2.6

    Kernel preparation unnecessary for this kernel.  Skipping...

    Building module:
    cleaning build area...
    KDIR=/lib/modules/4.19.81/build MDIR=/lib/modules/4.19.81 make SKIP_STACK_VALIDATION=1....(bad exit status: 2)
    Error! Bad return status for module build on kernel: 4.19.81 (i686)
    Consult /var/lib/dkms/ncpfs/2.2.6/build/make.log for more information.

    $ $ cat /var/lib/dkms/ncpfs/2.2.6/build/make.log
    DKMS make.log for ncpfs-2.2.6 for kernel 4.19.81 (i686)
    Wed Nov  6 01:27:29 MSK 2019
    make -C /lib/modules/4.19.81/build M=/var/lib/dkms/ncpfs/2.2.6/build modules
    make[1]: Entering directory '/usr/src/linux-4.19.81'
      CC [M]  /var/lib/dkms/ncpfs/2.2.6/build/dir.o
      CC [M]  /var/lib/dkms/ncpfs/2.2.6/build/file.o
      CC [M]  /var/lib/dkms/ncpfs/2.2.6/build/inode.o
      CC [M]  /var/lib/dkms/ncpfs/2.2.6/build/ioctl.o
      CC [M]  /var/lib/dkms/ncpfs/2.2.6/build/mmap.o
    /var/lib/dkms/ncpfs/2.2.6/build/mmap.c:99:11: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
      .fault = ncp_file_mmap_fault,
               ^~~~~~~~~~~~~~~~~~~
    /var/lib/dkms/ncpfs/2.2.6/build/mmap.c:99:11: note: (near initialization for 'ncp_file_mmap.fault')
    cc1: some warnings being treated as errors
    scripts/Makefile.build:303: recipe for target '/var/lib/dkms/ncpfs/2.2.6/build/mmap.o' failed
    make[2]: *** [/var/lib/dkms/ncpfs/2.2.6/build/mmap.o] Error 1
    Makefile:1519: recipe for target '_module_/var/lib/dkms/ncpfs/2.2.6/build' failed
    make[1]: *** [_module_/var/lib/dkms/ncpfs/2.2.6/build] Error 2
    make[1]: Leaving directory '/usr/src/linux-4.19.81'
    Makefile:48: recipe for target 'all' failed
    make: *** [all] Error 2

**Comment by EnzephaloN** [comment]
Hello @phdru :

You tried the last version master?
This won't work, because latest master is patched for kernel >=5.2.

Please try former commits, like
https://github.com/EnzephaloN/ncpfs_dkms/commit/151838290c145608636312d3da49e8602932e716 (which was for kernel 4.20)
or
https://github.com/EnzephaloN/ncpfs_dkms/commit/fe4dd5f1f9922d1dcd2637c53524314bae82c022 (which was for kernel >=4.16)

Please let me know if it works.
Best regards
EnzephaloN

**Comment by phdru** [comment]
Yep, commit 77f34ba compiled:

    $ sudo dkms build -k 4.19.81 -m ncpfs -v 2.2.6

    Kernel preparation unnecessary for this kernel.  Skipping...

    Building module:
    cleaning build area.......
    KDIR=/lib/modules/4.19.81/build MDIR=/lib/modules/4.19.81 make........
    cleaning build area...

    DKMS: build completed.

Thank you very much! Gonna reboot and try it…
