### ISSUE TITLE
Error compile on kernel 5.18.19-051819-generic (x86_64)

### ISSUE THREAD

**Issue by malec0101** [EnzephaloN/ncpfs_dkms#11]
Building module:
cleaning build area...
KDIR=/lib/modules/5.18.19-051819-generic/build MDIR=/lib/modules/5.18.19-051819-generic make SKIP_STACK_VALIDATION=1......(bad exit status: 2)
ERROR (dkms apport): binary package for ncpfs: 2.2.6 not found
Error! Bad return status for module build on kernel: 5.18.19-051819-generic (x86_64)
Consult /var/lib/dkms/ncpfs/2.2.6/build/make.log for more information

cat /var/lib/dkms/ncpfs/2.2.6/build/make.log
DKMS make.log for ncpfs-2.2.6 for kernel 5.18.19-051819-generic (x86_64)
Пан 26 вер 2022 14:45:31 +03
make -C /lib/modules/5.18.19-051819-generic/build M=/var/lib/dkms/ncpfs/2.2.6/build modules
make[1]: вход в каталог «/usr/src/linux-headers-5.18.19-051819-generic»
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: gcc (Ubuntu 11.3.0-5ubuntu1) 11.3.0
  You are using:           gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0
  CC [M]  /var/lib/dkms/ncpfs/2.2.6/build/dir.o
  CC [M]  /var/lib/dkms/ncpfs/2.2.6/build/file.o
  CC [M]  /var/lib/dkms/ncpfs/2.2.6/build/inode.o
  CC [M]  /var/lib/dkms/ncpfs/2.2.6/build/ioctl.o
  CC [M]  /var/lib/dkms/ncpfs/2.2.6/build/mmap.o
  CC [M]  /var/lib/dkms/ncpfs/2.2.6/build/ncplib_kernel.o
  CC [M]  /var/lib/dkms/ncpfs/2.2.6/build/sock.o
  CC [M]  /var/lib/dkms/ncpfs/2.2.6/build/ncpsign_kernel.o
  CC [M]  /var/lib/dkms/ncpfs/2.2.6/build/getopt.o
  CC [M]  /var/lib/dkms/ncpfs/2.2.6/build/symlink.o
/var/lib/dkms/ncpfs/2.2.6/build/symlink.c:103:10: error: ‘const struct address_space_operations’ has no member named ‘read_folio’
  103 |         .read_folio = ncp_symlink_read_folio,
      |          ^~~~~~~~~~
/var/lib/dkms/ncpfs/2.2.6/build/symlink.c:103:23: error: initialization of ‘int (*)(struct page *, struct writeback_control *)’ from incompatible pointer type ‘int (*)(struct file *, struct folio *)’ [-Werror=incompatible-pointer-types]
  103 |         .read_folio = ncp_symlink_read_folio,
      |                       ^~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/ncpfs/2.2.6/build/symlink.c:103:23: note: (near initialization for ‘ncp_symlink_aops.writepage’)
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:289: /var/lib/dkms/ncpfs/2.2.6/build/symlink.o] Ошибка 1
make[1]: *** [Makefile:1850: /var/lib/dkms/ncpfs/2.2.6/build] Ошибка 2
make[1]: выход из каталога «/usr/src/linux-headers-5.18.19-051819-generic»
make: *** [Makefile:48: all] Ошибка 2

**Comment by EnzephaloN** [comment]
Hello

You're on kernel 5.18, so you have to use branch [kernel_5.15](https://github.com/EnzephaloN/ncpfs_dkms/tree/kernel_5.15) instead of master! Documentation is wrong at this point, sorry.

Best regards

EnzephaloN

**Comment by malec0101** [comment]
Thanks a lot. Your work is very valuable.

**Comment by malec0101** [comment]
I can't use the module's functions.  ncpmount, slist won't start.  Do you need additional software?

**Comment by malec0101** [comment]
I can't use the module's functions.  ncp mount, list doesn't run.  Does the module require additional software?

**Comment by malec0101** [comment]
I can't use the module's functions.  ncpmount, slist doesn't run.  Does the module require additional software?

**Comment by EnzephaloN** [comment]
This is just the "filesystem-driver". The ncpfsutils are not included. Maybe you can find them on older linux distributions (for example maybe here: https://packages.altlinux.org/en/p8/srpms/ncpfs/rpms/ ). you need /usr/bin/ncplogin, /usr/bin/ncplogout, /usr/bin/ncpmap, /usr/bin/ncpmount and /usr/bin/ncpumount. Also you need a symlink /usr/sbin/mount.ncpfs -> /usr/bin/ncpmount .

**Comment by malec0101** [comment]
I assumed so.  I am using Ubuntu 22.04.  At the moment, I was unable to install older versions of the ncpfs package.  At the installation stage, it shows an unpacking error.  Installing from source code will crash.  Apparently a deb package is needed that will suit my system.  Thank you very much for your support and advice.

**Comment by EnzephaloN** [comment]
I think it's a bit too tricky to find a deb-package...
Maybe this works:
Grab http://ftp.altlinux.org/pub/distributions/ALTLinux/p8/branch/files/x86_64/RPMS/ncpfs-2.2.6-alt9.qa1.x86_64.rpm and unpack it. Inside in /usr/bin you will find the binaries I pointed above.
